### ISSUE TITLE
Tooltip with StackedBar not being rendered

### ISSUE THREAD

**Issue by juanpaucar** [eventbrite/britecharts-react#150]
## Expected Behavior
When I add a Tooltip for a StackedBar, I expect the tooltip being rendered along with the chart. This is also happening to me on Bar charts. 

## Current Behavior
The tooltip is not being rendered. I created a small pen to show you the behavior. I started from a similar pen which worked for Line charts. 

The chart is being rendered, but the tooltip is not being rendered.

## Possible Solution
Not sure, if it's not implemented yet or if it should be rendered but I'm missing something. I thought that the tooltip worked since on the documentation there's this mention:

> The tooltip component is a great companion to the line, stacked area, stacked bar and grouped bar charts.

## Steps to Reproduce (for bugs)
Please, check this pen: https://codepen.io/juanpaucar/pen/maJrgQ

## Context
I just started using this charts and it seemed weird to me that they don't work for Bar and Stacked Bar.

## Your Environment
Ubuntu 18.04
Node 10.13.0
Britecharts and Britecharts-react latests versions
https://codepen.io/juanpaucar/pen/maJrgQ

**Comment by Golodhros** [comment]
Hi @juanpaucar, thanks for opening this issue!

I just noticed we don't have an example of this in the docs. In theory, it should work but I don't discard there is an issue somewhere.

I will try to work it out in the demos and then come back to you here.

Thanks again!

**Comment by juanpaucar** [comment]
Hi, thank you guys for the wrapper and the library itself. I thought I was doing something wrong... or am I 🤔

**Comment by davegomez** [comment]
I can confirm that the [tooltip is not being rendered with the StackedBar chart](https://codesandbox.io/s/4k76jy9z4) and is not throwing any error either. Gonna take a look.

**Comment by davegomez** [comment]
@Golodhros this should be mark as a bug.

I've been playing with the charts and found that GroupedBar and StackedBar are not calling `componentDidUpdate` after the initial render, so the method `createTooltip` is never called for these charts.

**Comment by Golodhros** [comment]
Thanks for the debugging @davegomez!!

**Comment by Dezzymei** [comment]
Is there a way to do this then? I might look for a different solution if this library is not complete...

**Comment by davegomez** [comment]
This is already fixed in the PR #163

**Comment by Golodhros** [comment]
It seems we still have some issues. If you check on https://eventbrite.github.io/britecharts-react/#!/StackedBar/5, the tooltip only shows when we are hovering outside the stacked bars.

**Comment by davegomez** [comment]
This is a good case for it was working for me... gonna take a look on that today. Thanks for the demo 🙂 @Golodhros

**Comment by Golodhros** [comment]
Thanks a lot @davegomez! You are really making a dent in Britecharts-React!
